source "https://github.com/TKCocoapods/tkcp-spec"

use_frameworks!

platform :ios, '9.0'

target 'TKCPSpeaker_Example' do
  pod 'TKCPSpeaker', :path => '../'

  target 'TKCPSpeaker_Tests' do
    inherit! :search_paths

    
  end
end
