# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "git@github.com:TKCocoapods/tkcp-spec.git"

target 'CocoapodsModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for CocoapodsModuleDemo
  pod 'TKCPSpeaker', :path => '../TKCPSpeaker/'
  pod 'TKCPBasket', :path => '../TKCPBasket/'
  pod 'TKCPDog', :path => '../TKCPDog/'
end
