# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://github.com/TKCocoapods/tkcp-spec"

target 'CocoapodsModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsModuleDemo
  pod 'TKCPSpeaker', :path => '../TKCPSpeaker/'
end
